name: Payyap Mobile Automation

on:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 24

      - name: Install dependencies
        run: npm install

      - name: Run Android Emulator
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: 34
          target: google_apis
          arch: x86_64
          emulator-options: -no-window -no-audio -no-boot-anim -gpu swiftshader_indirect
          disable-animations: true
          script: |
            echo "Checking Android emulator..."

            adb wait-for-device

            echo "Waiting for Android boot to complete..."

            for i in {1..60}; do
              BOOT_COMPLETED=$(adb shell getprop sys.boot_completed 2>/dev/null | tr -d '\r')

              if [ "$BOOT_COMPLETED" = "1" ]; then
                echo "Android emulator boot completed."
                break
              fi

              echo "Waiting for emulator... ($i/60)"
              sleep 5
            done

            echo "Connected devices:"
            adb devices

            echo "Android version:"
            adb shell getprop ro.build.version.release

            echo "SDK version:"
            adb shell getprop ro.build.version.sdk

            echo "Installing Payyap APK..."
            adb install -r Payyap.apk

            echo "Starting WDIO tests..."
            npx wdio run wdio.conf.js --spec ./test/specs/TC01_LoginHome.e2e.js

      - name: Generate Allure Report
        if: always()
        run: npx allure-commandline generate allure-results --clean -o allure-report

      - name: Upload Allure Report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: payyap-allure-report
          path: allure-report/