name: Payyap Mobile Automation

on:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 24

      - name: Install dependencies
        run: npm install

      - name: Run Android Emulator
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: 35
          target: google_apis
          arch: x86_64
          profile: Pixel_2
          emulator-options: -no-window -no-audio -no-boot-anim -gpu swiftshader_indirect
          disable-animations: true
          script: |
            adb wait-for-device

            echo "Waiting for Android emulator to boot..."

            until adb shell getprop sys.boot_completed | tr -d '\r' | grep -q "1"; do
              sleep 5
            done

            echo "Android emulator boot completed!"

            adb devices

            adb install -r Payyap.apk

            npx wdio run wdio.conf.js --spec ./test/specs/TC01_LoginHome.e2e.js