name: Payyap Mobile Automation

on:
  workflow_dispatch:

jobs:
  test:
    runs-on: self-hosted
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Run WebdriverIO Tests
        run: |
          npm install
          npx wdio run wdio.conf.js
